import { AssetPreset, parseAssetId } from './index';

function assets(ids: string[]) {
  return ids.map(parseAssetId);
}

export const ASSET_PRESETS: AssetPreset[] = [
  {
    id: 'binance-top',
    name: 'Binance Crypto Top',
    description: 'Liquid USDT majors on Binance (decoupling vs BTC).',
    preferredInterval: '4h',
    benchmarkId: 'binance:BTCUSDT',
    assets: assets([
      'binance:ETHUSDT',
      'binance:SOLUSDT',
      'binance:BNBUSDT',
      'binance:XRPUSDT',
      'binance:ADAUSDT',
      'binance:AVAXUSDT',
      'binance:LINKUSDT',
      'binance:DOTUSDT',
      'binance:NEARUSDT',
      'binance:ATOMUSDT',
      'binance:LTCUSDT',
      'binance:UNIUSDT',
      'binance:AAVEUSDT',
      'binance:INJUSDT',
      'binance:SUIUSDT',
      'binance:APTUSDT',
      'binance:ARBUSDT',
      'binance:OPUSDT',
      'binance:FILUSDT',
      'binance:TONUSDT',
    ]),
  },
  {
    id: 'hyperliquid-majors',
    name: 'Hyperliquid Majors',
    description: 'HL perpetuals including HYPE. Free public candle API.',
    preferredInterval: '4h',
    benchmarkId: 'hyperliquid:BTC',
    assets: assets([
      'hyperliquid:BTC',
      'hyperliquid:ETH',
      'hyperliquid:SOL',
      'hyperliquid:HYPE',
      'hyperliquid:BNB',
      'hyperliquid:XRP',
      'hyperliquid:DOGE',
      'hyperliquid:AVAX',
      'hyperliquid:LINK',
      'hyperliquid:ARB',
      'hyperliquid:SUI',
      'hyperliquid:APT',
      'hyperliquid:WIF',
      'hyperliquid:PEPE',
    ]),
  },
  {
    id: 'macro-commodities',
    name: 'Macro Commodities',
    description: 'Gold, silver, oil, copper, natgas futures via Yahoo (daily).',
    preferredInterval: '1d',
    benchmarkId: 'yahoo:GC=F',
    assets: assets([
      'yahoo:GC=F',
      'yahoo:SI=F',
      'yahoo:CL=F',
      'yahoo:BZ=F',
      'yahoo:HG=F',
      'yahoo:NG=F',
      'yahoo:PA=F',
      'yahoo:PL=F',
    ]),
  },
  {
    id: 'metals-energy',
    name: 'Metals & Energy',
    description: 'Precious metals + crude oil + gas. Daily bars.',
    preferredInterval: '1d',
    benchmarkId: 'yahoo:GC=F',
    assets: assets([
      'yahoo:GC=F',
      'yahoo:SI=F',
      'yahoo:PL=F',
      'yahoo:PA=F',
      'yahoo:CL=F',
      'yahoo:BZ=F',
      'yahoo:NG=F',
    ]),
  },
  {
    id: 'fx-majors',
    name: 'FX Majors',
    description: 'USD pairs via Yahoo (=X). Daily.',
    preferredInterval: '1d',
    benchmarkId: 'yahoo:EURUSD=X',
    assets: assets([
      'yahoo:EURUSD=X',
      'yahoo:GBPUSD=X',
      'yahoo:USDJPY=X',
      'yahoo:AUDUSD=X',
      'yahoo:USDCAD=X',
      'yahoo:USDCHF=X',
      'yahoo:NZDUSD=X',
    ]),
  },
  {
    id: 'multi-asset',
    name: 'Multi-Asset Basket',
    description: 'Crypto + gold + oil + silver. Cross-market daily agent.',
    preferredInterval: '1d',
    benchmarkId: 'binance:BTCUSDT',
    assets: assets([
      'binance:BTCUSDT',
      'binance:ETHUSDT',
      'hyperliquid:HYPE',
      'hyperliquid:SOL',
      'yahoo:GC=F',
      'yahoo:SI=F',
      'yahoo:CL=F',
      'yahoo:NG=F',
    ]),
  },
  {
    id: 'paper-cross-asset',
    name: 'Paper Cross-Asset (Recommended)',
    description: 'Agent paper: crypto majors + gold + silver + oil. Long/short momentum+decoupling.',
    preferredInterval: '1d',
    benchmarkId: 'binance:BTCUSDT',
    assets: assets([
      'binance:BTCUSDT',
      'binance:ETHUSDT',
      'binance:SOLUSDT',
      'hyperliquid:HYPE',
      'yahoo:GC=F',
      'yahoo:SI=F',
      'yahoo:CL=F',
      'yahoo:NG=F',
      'yahoo:HG=F',
    ]),
  },
];

export function getPresetById(id: string): AssetPreset | undefined {
  return ASSET_PRESETS.find((p) => p.id === id);
}
