import { buildSupervisorPayload, ruleSupervisorFallback } from '../lib/quant/supervisorInsight';

const payload = buildSupervisorPayload([
  {
    agentId: 'crypto',
    running: true,
    equity: 993,
    cash: 993,
    openPositions: 3,
    totalTrades: 8,
    winRate: 13,
    pnlPercent: -0.7,
    paceMonthlyPercent: 0,
    kpiStatus: 'behind',
    activity: 'Monitoring open: LONG BNB, LONG XRP, LONG NEAR',
    updatedAt: Date.now(),
    monthlyTargetLow: 0.1,
    monthlyTargetHigh: 0.5,
    capitalStart: 1000,
    recentTrades: [
      { symbol: 'binance:BNBUSDT', side: 'long', pnl: -0.98, pnlPercent: -0.1, exitReason: 'time_stop' },
    ],
    openList: [
      { symbol: 'binance:BNBUSDT', side: 'long', entryPrice: 1, unrealizedPnl: -1 },
      { symbol: 'binance:XRPUSDT', side: 'long', entryPrice: 1, unrealizedPnl: 0 },
      { symbol: 'binance:NEARUSDT', side: 'long', entryPrice: 1, unrealizedPnl: 0 },
    ],
    lastActivityLog: [],
    equityHistory: [{ time: Date.now() - 3600000, equity: 1000 }, { time: Date.now(), equity: 993 }],
  },
  {
    agentId: 'commodities',
    running: true,
    equity: 994.4,
    cash: 994.4,
    openPositions: 3,
    totalTrades: 9,
    winRate: 11,
    pnlPercent: -0.56,
    paceMonthlyPercent: 0,
    kpiStatus: 'behind',
    activity: 'LONG CL, BZ, NG',
    updatedAt: Date.now(),
    monthlyTargetLow: 0.08,
    monthlyTargetHigh: 0.35,
    capitalStart: 1000,
    recentTrades: [
      { symbol: 'yahoo:CL=F', side: 'long', pnl: -0.87, pnlPercent: -0.09, exitReason: 'time_stop' },
    ],
    openList: [
      { symbol: 'yahoo:CL=F', side: 'long', entryPrice: 90 },
      { symbol: 'yahoo:BZ=F', side: 'long', entryPrice: 90 },
      { symbol: 'yahoo:NG=F', side: 'long', entryPrice: 3 },
    ],
    lastActivityLog: [],
    equityHistory: [{ time: Date.now() - 3600000, equity: 1000 }, { time: Date.now(), equity: 994.4 }],
  },
  {
    agentId: 'gold-silver',
    running: true,
    equity: 997.4,
    cash: 997.4,
    openPositions: 2,
    totalTrades: 4,
    winRate: 25,
    pnlPercent: -0.26,
    paceMonthlyPercent: 0,
    kpiStatus: 'behind',
    activity: 'LONG CL, BZ',
    updatedAt: Date.now(),
    monthlyTargetLow: 0.05,
    monthlyTargetHigh: 0.25,
    capitalStart: 1000,
    recentTrades: [
      { symbol: 'yahoo:CL=F', side: 'long', pnl: -1.01, pnlPercent: -0.1, exitReason: 'time_stop' },
    ],
    openList: [
      { symbol: 'yahoo:CL=F', side: 'long', entryPrice: 90 },
      { symbol: 'yahoo:BZ=F', side: 'long', entryPrice: 90 },
    ],
    lastActivityLog: [],
    equityHistory: [{ time: Date.now() - 3600000, equity: 1000 }, { time: Date.now(), equity: 997.4 }],
  },
]);

console.log(ruleSupervisorFallback(payload));
